In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [22]:
df=pd.read_csv(r"/content/drive/MyDrive/Colab Notebooks/Projects/CSV/car_evaluation.csv",header=None)

In [23]:
df.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [24]:
df.shape

(1728, 7)

In [25]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [26]:
df.columns=col_names
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='object')

In [27]:
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [29]:
for col in col_names:
  print(df[col].value_counts())

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64
persons
2       576
4       576
more    576
Name: count, dtype: int64
lug_boot
small    576
med      576
big      576
Name: count, dtype: int64
safety
low     576
med     576
high    576
Name: count, dtype: int64
class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64


In [30]:
df["class"].value_counts()

class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [31]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [32]:
##No use of selecting only dtypes of object

#from sklearn import preprocessing
#df_cat=df.select_dtypes(include=['object'])
#df_cat.head()

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df=df.apply(le.fit_transform)
df.head()

buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [34]:
#df=df.drop(df_cat.columns,axis=1)
#df=pd.concat([df,df_cat],axis=1)
#df.head()

In [35]:
X=df.drop(['class'],axis=1)
y=df['class']

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)


In [37]:
X_train.shape, X_test.shape

((1209, 6), (519, 6))

In [38]:

from sklearn.preprocessing import LabelEncoder as le


In [39]:
from sklearn.tree import DecisionTreeClassifier
import sklearn.tree as tree

In [51]:
#HyperParameter tuning
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
n_folds=5
param_grid={'max_depth':range(5,15,5),'min_samples_leaf':range(50,150,50),'min_samples_split':range(50,150,50),'criterion':['entropy','gini']}
dt=DecisionTreeClassifier()
grid_Search=GridSearchCV(estimator=dt,param_grid=param_grid,cv=n_folds,verbose=3)
grid_Search.fit(X_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV 1/5] END criterion=entropy, max_depth=5, min_samples_leaf=50, min_samples_split=50;, score=0.818 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, min_samples_leaf=50, min_samples_split=50;, score=0.789 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, min_samples_leaf=50, min_samples_split=50;, score=0.822 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, min_samples_leaf=50, min_samples_split=50;, score=0.781 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, min_samples_leaf=50, min_samples_split=50;, score=0.793 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, min_samples_leaf=50, min_samples_split=100;, score=0.818 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, min_samples_leaf=50, min_samples_split=100;, score=0.789 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, min_samples_leaf=50, min_samples_split=100;, score=0

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': range(5, 15, 5),
                         'min_samples_leaf': range(50, 150, 50),
                         'min_samples_split': range(50, 150, 50)},
             verbose=3)

In [52]:
print("Best accuracy:",grid_Search.best_score_)
print(grid_Search.best_estimator_)

Best accuracy: 0.8006549843969687
DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_leaf=50,
                       min_samples_split=50)


In [53]:
dtree=DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_leaf=50,
                       min_samples_split=50)
dtree.fit(X_train,y_train)


DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_leaf=50,
                       min_samples_split=50)

In [56]:
y_pred_test=dtree.predict(X_test)

In [61]:
from sklearn import metrics
print("Testing set Accuracy score:",metrics.accuracy_score(y_test,pred_tree))

Testing set Accuracy score: 0.838150289017341


In [58]:
y_pred_train = dtree.predict(X_train)

In [60]:
print('Training-set Accuracy score: {0:0.4f}'. format(metrics.accuracy_score(y_train,y_pred_train)))

Training-set Accuracy score: 0.8213


# Checking for Overfitting

We can see that the training-set score and test-set score is same as above. The training-set accuracy score is 0.7865 while the test-set accuracy to be 0.8021. These two values are quite comparable. So, there is no sign of overfitting.


In [65]:
from sklearn.tree import export_graphviz
export_graphviz(dtree,filled=True,feature_names=X_train.columns,out_file='tree.dot')
!dot -Tpng tree.dot -o tree.png

Confusion Matrix

In [68]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_test)
print("Confusion Matrix:\n\n",cm)

Confusion Matrix:

 [[ 81   0  23  14]
 [ 10   0   0   9]
 [ 27   0 330   1]
 [  0   0   0  24]]


Classification Report

In [69]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.69      0.69      0.69       118
           1       0.00      0.00      0.00        19
           2       0.93      0.92      0.93       358
           3       0.50      1.00      0.67        24

    accuracy                           0.84       519
   macro avg       0.53      0.65      0.57       519
weighted avg       0.82      0.84      0.83       519

